### PR TITLE
Stop using @opensuse.org addresses to indicate a missing address

### PR DESCRIPTION
**Pull request by jengelh**

### CODE REVIEW

**Comment by jengelh** [comment]
review reminder? @aspiers

**Comment by jengelh** [comment]
I guess they don't get PR notifications either. The github system is terrible in that regard :-/

**Comment by jengelh** [comment]
> I would even go one step further, we should fail when no email adress is configured.

Waiting for your patch; meanwhile, please approve ;-)

**Comment by aspiers** [comment]
[**@adrianschroeter**](https://github.com/adrianschroeter) [commented](https://github.com/openSUSE/obs-service-tar_scm/pull/260#issuecomment-457179310 "2019-01-24T12:27:02Z - Replied by Github Reply Comments"):
> I would even go one step further, we should fail when no email adress is configured.
> 
> We really want to have only valid adresses where a person (or a group) is behind.

Agreed.

**Pull request merged**
