### PR TITLE
Allow to manually specify a base for @TAG_OFFSET@

### PR DESCRIPTION
**Pull request by jengelh**
This permits to use, in the _service file,

	<param name="parent-tag">(hash of root commit)</param>
	<param name="versionformat">1.2.3.@TAG_OFFSET@.%h</param>

and get a monotonically increasing number (for the particular
branch it draws from).

### CODE REVIEW

**Comment by aspiers** [comment]
Looks great, thanks!  Please could you add some tests though?

**Comment by jengelh** [comment]
updated.

**Comment by aspiers** [comment]
Fantastic!  Please can you squash the two commits together, then this will be good to merge.  Thanks again :-)

**Comment by jengelh** [comment]
Do you get autonotifications for pushed updates?

**Comment by jengelh** [comment]
redone.

**Comment by aspiers** [comment]
Sorry this took so long to merge! I don't know why I didn't notice that it got updated :-/

**Pull request merged**
