### PR TITLE
Add parameters to format @PARENT_TAG@ with re.sub

### PR DESCRIPTION
**Pull request by denisok**
Looking to number of PRs to change format of @PARENT_TAG@ I decided to add some entropy and submit one that is based on re.sub which might solve all the issues.

### CODE REVIEW

**Comment by denisok** [comment]
Fixes #92 
Reference: #114

**Comment by bluca** [comment]
@aspiers @adrianschroeter  ping :-) Any chance you guys could have a look at this, when you have a moment? It adds support for regex as requested on #114. Would really help a lot to have a solution for #92 as it's quite limiting for building from git repositories. Thanks!

**Comment by denisok** [comment]
@aspiers @adrianschroeter any chance to review?

**Comment by bluca** [comment]
A similar solution seems to have been deployed on build.opensuse.org, see https://github.com/openSUSE/obs-service-tar_scm/issues/111#issuecomment-291186606

**Comment by aspiers** [comment]
https://github.com/openSUSE/obs-service-tar_scm/pull/132/commits/960d0cebad3bbf86102991eb38c542bbf5a16df4 in #132 has just been merged which basically does the same thing so I think we can close this now.

**Pull request closed without merging**
