### PR TITLE
outdir must be an absolute path

### PR DESCRIPTION
**Pull request by frispete**
in order to correctly generate the tarball later on..

### CODE REVIEW

**Comment by aspiers** [comment]
Sorry everyone, somehow I missed this PR before.  I have no problem with this change, however I don't fully understand it.  @frispete Your commit message said that it's necessary "in order to correctly generate the tarball later on", but why is that exactly? Please could you update the commit message to give more detail? Thanks!

**Comment by hwoarang** [comment]
@aspiers since there is no activity here, would you perhaps consider https://github.com/openSUSE/obs-service-tar_scm/pull/107 which hopefully has a better commit message?

**Comment by frispete** [comment]
I vote for #107, since it is the better solution. 

With regard of realpath, I don't think, it makes a difference..

**Comment by aspiers** [comment]
Merged #107 instead.

**Pull request closed without merging**
