### PR TITLE
Remove code which corrupts versions

### PR DESCRIPTION
**Pull request by olafhering**
A _service file which intends to use @PARENT_TAG@ for the package
version, and which uses versionrewrite-pattern to process the tag
further, will be unable to process the full tag name to extract the
desired parts of it via versionrewrite-replacement. The reason is the
forced removal of all hyphens.

It is up to the author of the _service file how the final package
version is assembled. versionrewrite-pattern and
versionrewrite-replacement give control how this needs to be done.

Remove all of the offending code, which should have been removed along
with the changes that introduced versionrewrite in commit
960d0cebad3bbf86102991eb38c542bbf5a16df4.

Fixes issue #367

Signed-off-by: Olaf Hering <olaf@aepfle.de>

### CODE REVIEW

**Comment by hramrach** [comment]
Any progress here?

The failing test is python2 based. Is it even maintained? The failure looks like test setup problem.

**Comment by olafhering** [comment]
I can probably fix this by passing the property not as argument, but stuffing it somewhere else so that the actual consumers can grab it.

Any idea what place that would be?

**Comment by M0ses** [comment]
> The failing test is python2 based. Is it even maintained?

short answer: yes.
obs-service-tar_scm has to run (at least) on all maintained versions *SUSE versions (because of buildtime services).

> The failure looks like test setup problem.

Why? Because of pyhton2 support?

**Comment by M0ses** [comment]
> I can probably fix this by passing the property not as argument, but stuffing it somewhere else so that the actual consumers can grab it.
> 
> Any idea what place that would be?

I`m wondering if this should be something which the user should be able to configure, in this case a new parameter would be needed. @adrianschroeter : What do you think.

BTW: test cases would be useful to understand the problem better.

**Comment by hramrach** [comment]
Also it does not work. I applied the patch and I get version with a hyphen:

Index: mlxbf-bootctl.obsinfo
===================================================================
--- mlxbf-bootctl.obsinfo (revision 338286a3367c7b644f23bce59dabeff9)
+++ mlxbf-bootctl.obsinfo (working copy)
@@ -1,5 +1,5 @@
name: mlxbf-bootctl
-version: 1.16.11
+version: mlxbf-bootctl-1.1-6.11
mtime: 1601841854
commit: b6dd3501668c45020f1e81690cd53aa6e21289b0

Index: mlxbf-bootctl.spec
===================================================================
--- mlxbf-bootctl.spec (revision 338286a3367c7b644f23bce59dabeff9)
+++ mlxbf-bootctl.spec (working copy)
@@ -18,7 +18,7 @@


Name: mlxbf-bootctl
-Version: 1.16.11
+Version: mlxbf-bootctl-1.1-6.11
Release: 0
Summary: User-space driver for Mellanox BlueField SoC
License: BSD-2-Clause

**Comment by hramrach** [comment]
Also it breaks vesionrewrite-pattern

`



<services>
        <service name="obs_scm" mode="disabled">
                <param name="scm">git</param>
                <param name="url">https://github.com/Mellanox/mlxbf-bootctl.git</param>
                <param name="filename">mlxbf-bootctl</param>
                <param name="versionrewrite-pattern">mlxbfbootctl(.*)</param>
                <param name="versionformat">@PARENT_TAG@.@TAG_OFFSET@</param>
        </service>
        <service mode="disabled" name="set_version" />
        <service name="tar" mode="buildtime"/>
</services>
`

**Comment by olafhering** [comment]
What does it break? What is the input, what is the expected output?

The goal is to pass the tag verbatim into `versionrewrite-pattern`.

**Comment by hramrach** [comment]
Nevermind, the tag was previously butchered by removing hyphens and now it is not so the pattern must be amended to also contain the hyphens.

**Comment by olafhering** [comment]
> I`m wondering if this should be something which the user should be able to configure, in this case a new parameter would be needed. @adrianschroeter : What do you think.

You mean a `I really mean it` knob? Usage of `versionrewrite-pattern` and `versionrewrite-replacement` is already a clear instruction what is expected to happen.

**Comment by M0ses** [comment]
> > I`m wondering if this should be something which the user should be able to configure, in this case a new parameter would be needed. @adrianschroeter : What do you think.
> 
> You mean a `I really mean it` knob? Usage of `versionrewrite-pattern` and `versionrewrite-replacement` is already a clear instruction what is expected to happen.

Could you please explain the input and the expected output, in best case by a test case? I think I didn`t get the point of your commit.

**Comment by olafhering** [comment]
It must be possible to extract the individual parts of the verbatim tag. It is not up to tar_scm to decide if a hyphen is bad or not. That is entirely the responsibility of the `_service` file author, and a task of `versionrewrite-pattern` and `versionrewrite-replacement`.

**Comment by hramrach** [comment]
Indeed, it works with this service file:
```
<!-- See https://en.opensuse.org/openSUSE:Build_Service_Concept_SourceService -->
<!-- for more details on the syntax -->

<services>
        <service name="obs_scm" mode="disabled">
                <param name="scm">git</param>
                <param name="url">https://github.com/Mellanox/mlxbf-bootctl.git</param>
                <param name="filename">mlxbf-bootctl</param>
                <param name="versionrewrite-pattern">mlxbf-bootctl-(.*)-(.*)</param>
                <param name="versionrewrite-replacement">\1.\2</param>
                <param name="versionformat">@PARENT_TAG@.@TAG_OFFSET@</param>
        </service>
        <service mode="disabled" name="set_version" />
        <service name="tar" mode="buildtime"/>
</services>
```
Nonetheless, removing hyphens was done to prevent invalid version, and it does not happen automatically anymore. This could be seen as a regression.  Maybe an error should be reported when the resulting version contains a hyphen?

**Comment by olafhering** [comment]
rpm will report an error on bogus input.

**Comment by hramrach** [comment]
> > > I`m wondering if this should be something which the user should be able to configure, in this case a new parameter would be needed. @adrianschroeter : What do you think.
> > 
> > 
> > You mean a `I really mean it` knob? Usage of `versionrewrite-pattern` and `versionrewrite-replacement` is already a clear instruction what is expected to happen.
> 
> Could you please explain the input and the expected output, in best case by a test case? I think I didn`t get the point of your commit.

The problem is that upstream uses Debian style release tags such as 1.1-6 but does not adhere to the Debian policy to include only packaging changes in release (-n) and general changes in version (1.1). Hence the -n is significant. tar_scm further slaps the number of commits since the tag at the end 1.1-6.11 (as requested) and silently removes hyphens without any user control -> 1.16.11. This is clearly bogus. Trivially replacing the hyphen with dot gives valid version 1.1.6.11 but there is no way to achieve that with tar_scm.

**Comment by hramrach** [comment]
> rpm will report an error on bogus input.
Clearly there was an attempt to mitigate this in the service itself before that happens.

**Comment by M0ses** [comment]
I opened another PR how I would solve the problem without the risk of tons of broken packages

https://github.com/openSUSE/obs-service-tar_scm/pull/390

comments are welcome

**Comment by M0ses** [comment]
superseded by https://github.com/openSUSE/obs-service-tar_scm/commit/2fdf897c0579a8586a840ed0f681a610476345df

**Pull request closed without merging**
