### PR TITLE
be explicit about python2, python may be python3

### PR DESCRIPTION
**Pull request by roman-neuhauser**
like in ArchLinux

### CODE REVIEW

**Comment by aspiers** [comment]
Unfortunately this breaks the build on Debian :-(

https://build.opensuse.org/package/live_build_log/home:aspiers:branches:openSUSE:Tools/obs-service-tar_scm/Debian_7.0/x86_64

```
[   27s]    dh_auto_test
[   27s] 	make -j1 test
[   27s] make[1]: Entering directory `/usr/src/packages/BUILD'
[   27s] : Running the test suite.  Please be patient - this takes a few minutes ...
[   27s] PYTHONPATH=. python2 tests/test.py
[   27s] /bin/sh: 1: python2: not found
[   27s] make[1]: *** [test] Error 127
[   27s] make[1]: Leaving directory `/usr/src/packages/BUILD'
[   27s] dh_auto_test: make -j1 test returned exit code 2
[   27s] make: *** [build] Error 29
[   27s] dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

What was the exact motivation for this change?  If it fixed some breakage, I'd like to know details, otherwise I am tempted to revert it.

**Comment by roman-neuhauser** [comment]
@aspiers i'd say the code is *obviously* not 3.x-ready.  if you revert this you'll be trading broken Debian for broken ArchLinux.

```
 python ./tar_scm.py
  File "./tar_scm.py", line 57
    print line.rstrip()
             ^
SyntaxError: invalid syntax
```

there's a handful of these as well as

```
  File "./tar_scm.py", line 138
    except SystemExit, e:
                     ^
SyntaxError: invalid syntax
```

and that's just the immediately visible problems.

**Comment by aspiers** [comment]
> @aspiers i'd say the code is obviously not 3.x-ready.

Sure.

> if you revert this you'll be trading broken Debian for broken ArchLinux.

OK, that's the info I was looking for.  So you are saying that ArchLinux `/usr/bin/python` is version 3.

**Comment by roman-neuhauser** [comment]
the cover letter for this pull request is (see top of the page):

    be explicit about python2, python may be python3
    
    like in ArchLinux

**Comment by aspiers** [comment]
Yeah, sorry it wasn't immediately obvious to me from those three words.  I get it now.

**Pull request merged**
